#!/usr/bin/env python

import os
import sys
import requests
import ctypes
libc = ctypes.CDLL(None, use_errno=True)

chroot = sys.argv[1]
url = sys.argv[2]
ns = int(sys.argv[3])

# encodings are load lazily
# ''.encode('idna')

# punch through
print(requests.get(sys.argv[2]))

nsfds = []

if ns > 0:
  nspath = '/proc/{0}/ns'.format(ns)
  for n in os.listdir(nspath):
    if n == 'user':
      continue
    nsfds.append(open(os.path.join(nspath, n)))

os.chroot(sys.argv[1])

if ns > 0:
  for fd in nsfds:
    libc.setns(fd.fileno(), 0)

p = os.fork()
if p:
  print('waiting for: {0}'.format(p))
  print(os.wait())
else:
  print('executing: {0}'.format(os.getpid()))
  print(requests.get(sys.argv[2]))
